# French translations for oslo.concurrency.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the oslo.concurrency
# project.
#
# Translators:
# Maxime COQUEREL <max.coquerel@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version:  oslo.concurrency\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-09 06:08+0000\n"
"PO-Revision-Date: 2015-03-08 16:41+0000\n"
"Last-Translator: Maxime COQUEREL <max.coquerel@gmail.com>\n"
"Language-Team: French "
"(http://www.transifex.com/projects/p/osloconcurrency/language/fr/)\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: oslo_concurrency/lockutils.py:111
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""
"Impossible d'acquérir le verrou sur `%(filename)s` à cause de "
"%(exception)s"

#: oslo_concurrency/lockutils.py:208
msgid "Unable to release an unacquired lock"
msgstr "Impossible de libérer le verrou acquis %s"

#: oslo_concurrency/lockutils.py:671
msgid ""
"Calling lockutils directly is no longer supported.  Please use the "
"lockutils-wrapper console script instead."
msgstr ""
"Lockutils appelant directement n'est plus pris en charge. Merci "
"d'utiliser le script de la console lockutils -wrapper à la place."

#: oslo_concurrency/processutils.py:69
msgid "Unexpected error while running command."
msgstr "Erreur inattendue lors de l’exécution de la commande."

#: oslo_concurrency/processutils.py:72
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"Commande: %(cmd)s\n"
"Code de sortie: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"

#: oslo_concurrency/processutils.py:174
#, python-format
msgid "Got unknown keyword args: %r"
msgstr "Ags, mot clé inconnu: %r"

#: oslo_concurrency/processutils.py:177
#, python-format
msgid "Got invalid arg log_errors: %r"
msgstr "Argument reçu non valide log_errors: %r"

#: oslo_concurrency/processutils.py:183
msgid "Command requested root, but did not specify a root helper."
msgstr "La commande exigeait root, mais n'indiquait pas comment obtenir root."

#: oslo_concurrency/processutils.py:199
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "Exécution de la commande (sous-processus): %s"

#: oslo_concurrency/processutils.py:242
#, python-format
msgid ""
"%(desc)r\n"
"command: %(cmd)r\n"
"exit code: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"
msgstr ""
"%(desc)r\n"
"commande: %(cmd)r\n"
"Code de sortie: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"

#: oslo_concurrency/processutils.py:251
#, python-format
msgid ""
"Got an OSError\n"
"command: %(cmd)r\n"
"errno: %(errno)r"
msgstr ""
"Erreur du Système\n"
"commande: %(cmd)r\n"
"errno: %(errno)r"

#: oslo_concurrency/processutils.py:257
#, python-format
msgid "%r failed. Not Retrying."
msgstr "Echec de %r. Nouvelle tentative."

#: oslo_concurrency/processutils.py:261
#, python-format
msgid "%r failed. Retrying."
msgstr "Echec de %r. Nouvelle tentative."

#: oslo_concurrency/processutils.py:308
msgid "Environment not supported over SSH"
msgstr "Environnement non prise en charge sur SSH"

#: oslo_concurrency/processutils.py:312
msgid "process_input not supported over SSH"
msgstr "process_input non pris en charge sur SSH"

